version: '3'

dotenv: ['VERSION.env']

vars:
  APP_NAME: kali-mcp
  MAIN_PKG: ./cmd/
  TARGET_OS: '{{default "linux" .TARGET_OS}}'
  TARGET_ARCH: '{{default "amd64" .TARGET_ARCH}}'
  LDFLAGS: '-s -w -X github.com/nraintd/kali-mcp/internal/buildinfo.Version={{.VERSION}}'

env:
  CGO_ENABLED: '0'

silent: false

tasks:
  tidy:
    desc: 依赖整理
    cmds:
      - go mod tidy

  fmt:
    desc: 代码格式化
    cmds:
      - gofmt -w cmd internal
 
  gen:
    desc: 代码生成
    cmds:
      - go generate ./...

  test:
    desc: 运行测试
    env:
      GOOS: '{{.TARGET_OS}}'
      GOARCH: '{{.TARGET_ARCH}}'
    cmds:
      - go test ./...

  prepare:
    desc: 构建前准备(代码格式化 + 代码生成 + 测试)
    cmds:
      - task: tidy
      - task: fmt
      - task: test
        vars:
          TARGET_OS: '{{.TARGET_OS}}'
          TARGET_ARCH: '{{.TARGET_ARCH}}'
      - task: gen

  build:
    desc: 构建
    env:
      GOOS: '{{.TARGET_OS}}'
      GOARCH: '{{.TARGET_ARCH}}'
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o ./bin/{{.APP_NAME}}-{{.VERSION}}-{{.TARGET_OS}}-{{.TARGET_ARCH}} {{.MAIN_PKG}}
  
  build:all-arch:
    desc: 构建所有架构的可执行文件
    internal: true
    deps:
      - task: build
        vars:
          TARGET_ARCH: amd64
      - task: build
        vars:
          TARGET_ARCH: arm64
      - task: build
        vars:
          TARGET_ARCH: arm
      - task: build
        vars:
          TARGET_ARCH: 386
          
  build:release:
    desc: 构建发布版本（所有架构）
    deps:
      - task: build:all-arch

  build:dev:
    desc: 构建开发版本（所有架构）
    deps:
      - task: prepare
        vars:
          TARGET_OS: '{{.TARGET_OS}}'
          TARGET_ARCH: '{{.TARGET_ARCH}}'
    cmds:
      - task: build:all-arch

  clean:
    desc: 清理构建产物
    cmds:
      - go clean -cache -testcache
